kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-view
  labels:
    app: it-sample-view
spec:
  selector:
    matchLabels:
      deployment: it-sample-view
  template:
    metadata:
      labels:
        deployment: it-sample-view
        app: it-sample-view
    spec:
      containers:
        - name: sample-view
          image: image-registry.openshift-image-registry.svc:5000/rhn-support-jiadchen-dev/sample-view:9931368dbf4c9c1c76bc4bce44692220aaac7896
          env:
            - name: API_BASE_URL
              value: https://it-sample-app-rhn-support-jiadchen-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com
