kind: Deployment
apiVersion: apps/v1
metadata:
  name: sample-app
  labels:
    app: it-sample-app
spec:
  selector:
    matchLabels:
      deployment: it-sample-app
  template:
    metadata:
      labels:
        deployment: it-sample-app
        app: it-sample-app
    spec:
      containers:
        - name: sample-app
          image: image-registry.openshift-image-registry.svc:5000/rhn-support-jiadchen-dev/sample-app:b7ec51c307eb97579df5f62b928c0e90d6d02e95
